sudo: required
services:
  - docker

before_install:
  - docker build -t traviskirton/docker_ci_cd -f Dockerfile.dev .

script:
  - docker run -e CI=true traviskirton/docker_ci_cd npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: 'eu-west-1'
  app: 'docker_ci_cd'
  env: 'DockerCiCd-env'
  bucket_name: 'elasticbeanstalk-eu-west-1-434467771281'
  bucket_path: 'docker_ci_cd'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
